src_1 = '#bodyart #skinartmag #tattoolife #thebesttattooartists #blackandgrey #tattooedlife #inklife #besttattoos #tattooing #inkfreakz #blackandgreytattoo #tattoocommunity #nature_perfection #folkcreative #VisualsOfLife #gearednomad #MoodyGrams #visualambassadors #exklusive_shot #thecreative #peoplescreatives #sombresociety #royalsnappingartists #mskpit #mosquarium #moscowdays #moscowonline #insta_moskva #moscowdaily #bodyart #skinartmag #tattoolife #thebesttattooartists #blackandgrey #tattooedlife #inklife #besttattoos #tattooing #inkfreakz #blackandgreytattoo #tattoocommunity #nature_perfection #folkcreative #VisualsOfLife #gearednomad #MoodyGrams #visualambassadors #exklusive_shot #thecreative #peoplescreatives #sombresociety #royalsnappingartists #mskpit #mosquarium #moscowdays #moscowonline #insta_moskva #moscowdaily #bodyart #skinartmag #tattoolife #thebesttattooartists #blackandgrey #tattooedlife #inklife #besttattoos #tattooing #inkfreakz #blackandgreytattoo #tattoocommunity #inkedmag #tattooculture #inkaddict #tattoosociety #inkedlife #supportgoodtattooing #skinart #tattooedpeople #tattoolover #tattoos_alday #meistershots #mskpit #mosquarium #moscowdays #moscowonline #insta_moskva #moscowdaily #татухной #татушечка #татустудия #tattoos #татуировочка #татуировщик #inkwell #татуха #татумосква #татухи #татуировки #перманентныймакияж #татусалон #татуажбровей #эскиз #tattooed #tattooart #tattooartist #татуэскиз #татушки #тату #tattoo #татуажгуб #татувмоскве #татушка #татуажмосква #татуировка #tattoolife #татумастер #татуаж #тату #tattoo #татуировка #татуировки #татумастер #inkwell #tattoos #татуха #татуаж #татуировщик #татушка #татуэскиз #tattooed #татухи #татуировочка #татуажбровей #татушки #татушечка #татусалон #tattooartist #татустудия #татумосква #татуажгуб #перманентныймакияж #tattooart #татухной #татувмоскве #татуажмосква #tattoolife #эскиз'

src_2 = 'тфцшщвтфцщшвцтшгвф цв фв цфшвшгфцивзф9щцврз908врзо вцф шврфц90врф 0рв рф09зв8 р8цвфт фшщ9цв зр0фвц9 #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio #tatoo #tatoorealistic #tatoos #tatuagem #tatto #tattooistartmag #tattooist #tatooblack #tattoos #blackandgrey #realismotattoo #realismo #realtatoo #tattoos #tatooideas #tattoomodel #tatuagensmasculinas #tatuagemfeminina #tatuagemsombreada #tatuaggio'

import textdistance

# print(textdistance.jaccard.similarity(src_1, src_2))

import re

print('#' + ' #'.join(re.findall('#([a-zA-Z]+)', src_2)))